version: '3.9'
services:
  mongo:
      image: mongo:6
      container_name: mongo
      ports:
        - "27017:27017"

  server-app:
    build:
      context: .
      dockerfile: ./wk_server/Dockerfile
    environment:
      MONGO_URL: mongodb://mongo:27017/Worktime
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
    - mongo
    
  nginx:
    image: nginx:latest
    container_name: wk_nginx
    volumes:
      - ./nginx.conf:/etc/nginx.conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - server-app


  client-app:
    container_name: client-app
    volumes:
      - ./client/build:/code
    ports:
      - "3000:3000"
  
  admin-app:
    container_name: admin-app
    volumes:
      - ./admin/build:/code
    ports:
      - "4000:4000"