version: "3.8"

services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/server
      - /server/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
