services:
  admin:
    container_name: admin
    build:
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - admin
